#include "ml3_config.h"
#include "adc_precision.h"
#include "ml3_measurement.h"
#include "ml3_calibration.h"
#include "ml3_quality.h"
#include "ml3_payload.h"
#include "ml3_thermistor.h"
#include "ml3_at_commands.h"

#define ASSERT_ZERO_MACRO(name) typedef char assert_##name[(name == 0U) ? 1 : -1]
#define ASSERT_VALUE_MACRO(name, value) \
  typedef char assert_##name[(name == (value)) ? 1 : -1]

typedef char ml3_protocol_version_is_fixed[(ML3_CONFIG_PROTOCOL_VERSION == 1U) ? 1 : -1];
ASSERT_ZERO_MACRO(ML3_CONFIG_PAYLOAD_TYPE_ROUTINE);
typedef char ml3_payload_length_is_fixed[(ML3_CONFIG_PAYLOAD_LENGTH_ROUTINE == 25U) ? 1 : -1];
ASSERT_ZERO_MACRO(ML3_CONFIG_PAYLOAD_TYPE);
typedef char ml3_payload_length_is_fixed_alias[(ML3_CONFIG_PAYLOAD_LENGTH == 25U) ? 1 : -1];
typedef char ml3_mode_is_authorized[(ML3_CONFIG_MODE_ML3 == 10U) ? 1 : -1];
typedef char ml3_fport_is_authorized[(ML3_CONFIG_FPORT == 13U) ? 1 : -1];
typedef char ml3_mode_ready_is_authorized[(ML3_CONFIG_MODE_ML3_READY == 1U) ? 1 : -1];
typedef char ml3_fport_ready_is_authorized[(ML3_CONFIG_FPORT_READY == 1U) ? 1 : -1];
ASSERT_VALUE_MACRO(ML3_CONFIG_PB5_ACTIVE_LOW, 1U);
ASSERT_ZERO_MACRO(ML3_CONFIG_PB5_ACTIVE_LOW_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_PB5_RESET_ISP_BROWNOUT_SAFE);
ASSERT_ZERO_MACRO(ML3_CONFIG_PB5_RESET_ISP_BROWNOUT_SAFE_READY);
typedef char ml3_thermistor_adc_channel_is_pa2[
    (ML3_CONFIG_THERMISTOR_ADC_CHANNEL == 2U) ? 1 : -1];
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_ADC_CHANNEL_READY);
typedef char ml3_thermistor_excitation_is_pb4[
    (ML3_CONFIG_THERMISTOR_EXCITATION_GPIO == 4U) ? 1 : -1];
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_EXCITATION_GPIO_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_EFFECTIVE_REFERENCE_OHM);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_EFFECTIVE_REFERENCE_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_RAIL_GUARD_CODE);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_RAIL_GUARD_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_SETTLE_TIME_MS);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_SETTLE_TIME_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_TABLE_POINT_COUNT);
ASSERT_ZERO_MACRO(ML3_CONFIG_THERMISTOR_TABLE_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_ZERO_AMBIGUITY_GUARD_MV, 2U);
ASSERT_ZERO_MACRO(ML3_CONFIG_ZERO_AMBIGUITY_GUARD_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_CM_RANGE_MIN_MV, 0U);
ASSERT_VALUE_MACRO(ML3_CONFIG_CM_RANGE_MAX_MV, 100U);
ASSERT_ZERO_MACRO(ML3_CONFIG_CM_RANGE_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_V5_DIVIDER_RATIO_PPM, 500000U);
ASSERT_ZERO_MACRO(ML3_CONFIG_V5_DIVIDER_RATIO_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_V5_MINIMUM_MV, 4500U);
ASSERT_VALUE_MACRO(ML3_CONFIG_V5_MAXIMUM_MV, 5500U);
ASSERT_ZERO_MACRO(ML3_CONFIG_V5_LIMITS_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_DISCHARGE_THRESHOLD_MV, 500U);
ASSERT_VALUE_MACRO(ML3_CONFIG_DISCHARGE_TIMEOUT_MS, 2000U);
ASSERT_ZERO_MACRO(ML3_CONFIG_DISCHARGE_READY);
ASSERT_VALUE_MACRO(ML3_CONFIG_WARMUP_TIME_MS, 1500U);
ASSERT_ZERO_MACRO(ML3_CONFIG_WARMUP_TIME_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_LORA_REGION_ID);
ASSERT_ZERO_MACRO(ML3_CONFIG_LORA_REGION_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_LORA_DATARATE);
ASSERT_ZERO_MACRO(ML3_CONFIG_LORA_DATARATE_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_ROUTINE_MAX_AIRTIME_US);
ASSERT_ZERO_MACRO(ML3_CONFIG_ROUTINE_MAX_AIRTIME_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_DIAGNOSTIC_MAX_AIRTIME_US);
ASSERT_ZERO_MACRO(ML3_CONFIG_DIAGNOSTIC_MAX_AIRTIME_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_MAX_FRMPAYLOAD_BYTES);
ASSERT_ZERO_MACRO(ML3_CONFIG_MAX_FRMPAYLOAD_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_GATE0_APPROVAL_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_GATE1_APPROVAL_READY);
/*
 * task-F1 Step 3: Phase 2 qualification never produced a measured noise,
 * drift, or die-temperature threshold, so these are deliberately set
 * beyond any physically plausible reading (never a guessed "plausible"
 * number) and marked ready so quality evaluation can run at all - see the
 * rationale comment above these macros in ml3_config.h. Pin the actual
 * trial values so a future edit is a visible, deliberate diff here.
 */
ASSERT_VALUE_MACRO(ML3_CONFIG_NOISE_WARN_UV, 4000000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_NOISE_WARN_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_NOISE_INVALID_UV, 4200000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_NOISE_INVALID_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_WARMUP_DRIFT_WARN_UV, 4000000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_WARMUP_DRIFT_WARN_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_WARMUP_DRIFT_INVALID_UV, 4200000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_WARMUP_DRIFT_INVALID_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_VDDA_DRIFT_WARN_PPM, 900000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_VDDA_DRIFT_WARN_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_VDDA_DRIFT_INVALID_PPM, 950000U);
ASSERT_VALUE_MACRO(ML3_CONFIG_VDDA_DRIFT_INVALID_READY, 1U);
ASSERT_VALUE_MACRO(ML3_CONFIG_DIE_TEMP_MIN_CENTIC, -50000);
ASSERT_VALUE_MACRO(ML3_CONFIG_DIE_TEMP_MAX_CENTIC, 50000);
ASSERT_VALUE_MACRO(ML3_CONFIG_DIE_TEMP_RANGE_READY, 1U);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_OFFSET_UV);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_OFFSET_TEMPCO_UV_PER_C);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_GAIN_PPM);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_GAIN_TEMPCO_PPM_PER_C);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_CM_PPM);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_CM_REF_UV);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_OFFSET_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_GAIN_READY);
ASSERT_ZERO_MACRO(ML3_CONFIG_CAL_CM_READY);

#ifdef ML3_CONFIG_GATE0_READINESS_READY
#error "ML3_CONFIG_GATE0_READINESS_READY must be removed"
#endif
#ifdef ML3_CONFIG_CALIBRATION_READY
#error "ML3_CONFIG_CALIBRATION_READY must be removed"
#endif
#ifdef ML3_CONFIG_QUALIFICATION_READY
#error "ML3_CONFIG_QUALIFICATION_READY must be removed"
#endif
#ifdef ML3_CONFIG_PHASE2_QUALIFICATION_READY
#error "ML3_CONFIG_PHASE2_QUALIFICATION_READY must be removed"
#endif
#ifdef ML3_CONFIG_PHASE2_READINESS_READY
#error "ML3_CONFIG_PHASE2_READINESS_READY must be removed"
#endif
#ifdef ML3_CONFIG_CAL_V5_DIVIDER_PPM
#error "ML3_CONFIG_CAL_V5_DIVIDER_PPM must be removed"
#endif
#ifdef ML3_CONFIG_CAL_V5_DIVIDER_READY
#error "ML3_CONFIG_CAL_V5_DIVIDER_READY must be removed"
#endif

typedef char ml3_gate1_approval_is_zero[(ML3_CONFIG_GATE1_APPROVAL_READY == 0U) ? 1 : -1];

typedef char ml3_gate0_blocks_deployable[(ML3_CONFIG_DEPLOYABLE == 0U) ? 1 : -1];

int main(void)
{
  return 0;
}
