#ifndef ML3_CONFIG_H
#define ML3_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* Fixed protocol facts from Appendix A. */
#define ML3_CONFIG_PROTOCOL_VERSION            1U
#define ML3_CONFIG_PAYLOAD_TYPE_ROUTINE        0U
#define ML3_CONFIG_PAYLOAD_LENGTH_ROUTINE      25U
#define ML3_CONFIG_PAYLOAD_TYPE                ML3_CONFIG_PAYLOAD_TYPE_ROUTINE
#define ML3_CONFIG_PAYLOAD_LENGTH              ML3_CONFIG_PAYLOAD_LENGTH_ROUTINE

/* D2: authorized transport decision. Hardware qualification remains gated. */
#define ML3_CONFIG_MODE_ML3                    10U
#define ML3_CONFIG_FPORT                       13U
#define ML3_CONFIG_MODE_ML3_READY              1U
#define ML3_CONFIG_FPORT_READY                 1U

/* Gate 0 / Phase 1 hardware and build gates. */
#define ML3_CONFIG_PB5_ACTIVE_LOW              0U /* GATE0-PENDING (§2.1) */
#define ML3_CONFIG_PB5_ACTIVE_LOW_READY        0U /* GATE0-PENDING (§2.1) */
#define ML3_CONFIG_PB5_RESET_ISP_BROWNOUT_SAFE 0U /* GATE0-PENDING (§2.1) */
#define ML3_CONFIG_PB5_RESET_ISP_BROWNOUT_SAFE_READY 0U /* GATE0-PENDING (§2.1) */
#define ML3_CONFIG_THERMISTOR_ADC_CHANNEL      0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_ADC_CHANNEL_READY 0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_EXCITATION_GPIO  0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_EXCITATION_GPIO_READY 0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_ZERO_AMBIGUITY_GUARD_MV     0U /* GATE0-PENDING (§2.3) */
#define ML3_CONFIG_ZERO_AMBIGUITY_GUARD_READY  0U /* GATE0-PENDING (§2.3) */
#define ML3_CONFIG_CM_RANGE_MIN_MV             0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_CM_RANGE_MAX_MV             0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_CM_RANGE_READY              0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_V5_DIVIDER_RATIO_PPM        0U /* GATE0-PENDING (§3.4) */
#define ML3_CONFIG_V5_DIVIDER_RATIO_READY      0U /* GATE0-PENDING (§3.4) */
#define ML3_CONFIG_V5_MINIMUM_MV               0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_V5_MAXIMUM_MV               0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_V5_LIMITS_READY             0U /* GATE0-PENDING (§2.2) */
#define ML3_CONFIG_DISCHARGE_THRESHOLD_MV      0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_DISCHARGE_TIMEOUT_MS        0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_DISCHARGE_READY             0U /* GATE0-PENDING (§3.3) */
#define ML3_CONFIG_WARMUP_TIME_MS              0U /* GATE0-PENDING (§3.8) */
#define ML3_CONFIG_WARMUP_TIME_READY           0U /* GATE0-PENDING (§3.8) */
#define ML3_CONFIG_LORA_REGION_ID              0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_LORA_REGION_READY           0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_LORA_DATARATE               0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_LORA_DATARATE_READY         0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_MAX_FRMPAYLOAD_BYTES        0U /* GATE0-PENDING (§2.1 item 5, §3.13) */
#define ML3_CONFIG_MAX_FRMPAYLOAD_READY        0U /* GATE0-PENDING (§2.1 item 5, §3.13) */
#define ML3_CONFIG_ROUTINE_MAX_AIRTIME_US      0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_ROUTINE_MAX_AIRTIME_READY   0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_DIAGNOSTIC_MAX_AIRTIME_US   0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_DIAGNOSTIC_MAX_AIRTIME_READY 0U /* GATE0-PENDING (§3.13) */
#define ML3_CONFIG_GATE0_APPROVAL_READY        0U /* GATE0-PENDING (§2.6) */
#define ML3_CONFIG_GATE1_APPROVAL_READY        0U /* PHASE2-PENDING (§4.5) */

/* Phase 2 / Gate 1 qualification gates. */
/* The production temperature table stays absent until sourced from the ML3 manual (§3.3). */
#define ML3_CONFIG_THERMISTOR_EFFECTIVE_REFERENCE_OHM 0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_THERMISTOR_EFFECTIVE_REFERENCE_READY 0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_THERMISTOR_RAIL_GUARD_CODE 0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_RAIL_GUARD_READY 0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_SETTLE_TIME_MS   0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_SETTLE_TIME_READY 0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_TABLE_POINT_COUNT 0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_THERMISTOR_TABLE_READY      0U /* PHASE2-PENDING (§3.3) */
#define ML3_CONFIG_NOISE_WARN_UV               0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_NOISE_WARN_READY            0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_NOISE_INVALID_UV            0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_NOISE_INVALID_READY         0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_WARMUP_DRIFT_WARN_UV        0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_WARMUP_DRIFT_WARN_READY     0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_WARMUP_DRIFT_INVALID_UV     0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_WARMUP_DRIFT_INVALID_READY  0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_VDDA_DRIFT_WARN_PPM         0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_VDDA_DRIFT_WARN_READY       0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_VDDA_DRIFT_INVALID_PPM      0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_VDDA_DRIFT_INVALID_READY    0U /* PHASE2-PENDING (§4.2) */
#define ML3_CONFIG_DIE_TEMP_MIN_CENTIC         0U /* PHASE2-PENDING (§3.7) */
#define ML3_CONFIG_DIE_TEMP_MAX_CENTIC         0U /* PHASE2-PENDING (§3.7) */
#define ML3_CONFIG_DIE_TEMP_RANGE_READY        0U /* PHASE2-PENDING (§3.7) */
#define ML3_CONFIG_CAL_OFFSET_UV               0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_OFFSET_TEMPCO_UV_PER_C  0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_GAIN_PPM                0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_GAIN_TEMPCO_PPM_PER_C   0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_CM_PPM                  0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_CM_REF_UV               0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_OFFSET_READY            0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_GAIN_READY              0U /* PHASE2-PENDING (§3.10) */
#define ML3_CONFIG_CAL_CM_READY                0U /* PHASE2-PENDING (§3.10) */

#define ML3_CONFIG_PROTOCOL_READY \
  ((ML3_CONFIG_PROTOCOL_VERSION == 1U) && \
   (ML3_CONFIG_PAYLOAD_TYPE == 0U) && \
   (ML3_CONFIG_PAYLOAD_LENGTH == 25U))

#define ML3_CONFIG_GATE0_READINESS \
  (ML3_CONFIG_PB5_ACTIVE_LOW_READY && \
   ML3_CONFIG_PB5_RESET_ISP_BROWNOUT_SAFE_READY && \
   ML3_CONFIG_THERMISTOR_ADC_CHANNEL_READY && \
   ML3_CONFIG_THERMISTOR_EXCITATION_GPIO_READY && \
   ML3_CONFIG_ZERO_AMBIGUITY_GUARD_READY && \
   ML3_CONFIG_CM_RANGE_READY && \
   ML3_CONFIG_V5_DIVIDER_RATIO_READY && \
   ML3_CONFIG_V5_LIMITS_READY && \
   ML3_CONFIG_DISCHARGE_READY && \
   ML3_CONFIG_WARMUP_TIME_READY && \
   ML3_CONFIG_LORA_REGION_READY && \
   ML3_CONFIG_LORA_DATARATE_READY && \
   ML3_CONFIG_MAX_FRMPAYLOAD_READY && \
   ML3_CONFIG_ROUTINE_MAX_AIRTIME_READY && \
   ML3_CONFIG_DIAGNOSTIC_MAX_AIRTIME_READY && \
   ML3_CONFIG_GATE0_APPROVAL_READY)

#define ML3_CONFIG_PHASE2_READINESS \
  (ML3_CONFIG_THERMISTOR_EFFECTIVE_REFERENCE_READY && \
   ML3_CONFIG_THERMISTOR_RAIL_GUARD_READY && \
   ML3_CONFIG_THERMISTOR_SETTLE_TIME_READY && \
   ML3_CONFIG_THERMISTOR_TABLE_READY && \
   ML3_CONFIG_NOISE_WARN_READY && \
   ML3_CONFIG_NOISE_INVALID_READY && \
   ML3_CONFIG_WARMUP_DRIFT_WARN_READY && \
   ML3_CONFIG_WARMUP_DRIFT_INVALID_READY && \
   ML3_CONFIG_VDDA_DRIFT_WARN_READY && \
   ML3_CONFIG_VDDA_DRIFT_INVALID_READY && \
   ML3_CONFIG_DIE_TEMP_RANGE_READY && \
   ML3_CONFIG_CAL_OFFSET_READY && \
   ML3_CONFIG_CAL_GAIN_READY && \
   ML3_CONFIG_CAL_CM_READY && \
   ML3_CONFIG_GATE1_APPROVAL_READY)

/* Acquisition is a separate gate from selecting mode 10/FPort 13.  Keeping
 * it false until every measured input and qualification value is present
 * prevents a partially configured target from touching the stock ADC path. */
#define ML3_CONFIG_ACQUISITION_READY \
  ML3_CONFIG_GATE0_READINESS

#define ML3_CONFIG_DEPLOYABLE \
  (ML3_CONFIG_PROTOCOL_READY && \
   ML3_CONFIG_MODE_ML3_READY && \
   ML3_CONFIG_FPORT_READY && \
   ML3_CONFIG_GATE0_READINESS && \
   ML3_CONFIG_PHASE2_READINESS)

#ifdef __cplusplus
}
#endif

#endif /* ML3_CONFIG_H */
